# Generated by Django 3.0.2 on 2020-01-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
        ('comments', '0004_auto_20200126_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='slide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slides.Slide'),
        ),
    ]
