# Generated by Django 3.0.2 on 2020-01-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortForm', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_name',
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default='nowhere', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Department'),
        ),
    ]
