# Generated by Django 3.0.2 on 2020-01-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_location', models.CharField(help_text='Example: ON, CA', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_department', models.CharField(max_length=50)),
                ('course_term', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.School')),
            ],
        ),
    ]
