# Generated by Django 3.0.2 on 2020-01-26 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_courses_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='school_name',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
